### PR TITLE
Add Curia Vista Import Script

### PR DESCRIPTION
**Pull request by rettichschnidi**
Source: https://github.com/blank-tree/op-konzept
Commit: d52c6a5f55486916ccddb771ef971e913fb20492 (minus unrelated documents)

### CODE REVIEW

**Comment by rettichschnidi** [comment]
BTW: I am in favor of rewriting this thing. Which technology would be use ideally?

**Comment by esarbe** [comment]
What do you mean? Do you want to rewrite it in Scala?

**Comment by rettichschnidi** [comment]
Could be a nice (small, isolated) project for learning Scale. So yes. However, i do not know when *I* will have time...

**Comment by esarbe** [comment]
Let's merge it as it is and figure out a way forwards at a later point

**Pull request merged**
